<!-- R Commander Markdown Template -->

Replace with Main Title
=======================

### Your Name

### `r as.character(Sys.Date())`

```{r echo=FALSE}
# include this code chunk as-is to set options
knitr::opts_chunk$set(comment=NA, prompt=TRUE, out.width=750, fig.height=8, fig.width=8)
library(Rcmdr)
library(car)
library(RcmdrMisc)
```


```{r echo=FALSE}
# include this code chunk as-is to enable 3D graphs
library(rgl)
knitr::knit_hooks$set(webgl = hook_webgl)
```


```{r}
UniveralBank <- 
  read.table("C:/Users/rkrishnan/Documents/01 Personal/MS/SCM 651/week 8/scm651_homework_4_universal_bank.csv",
   header=TRUE, sep=",", na.strings="NA", dec=".", strip.white=TRUE)
```

```{r}
scatterplot(Age~PersonalLoan, regLine=FALSE, smooth=FALSE, boxplots=FALSE, 
  data=UniveralBank)
```

```{r}
scatterplot(Income~PersonalLoan, regLine=FALSE, smooth=FALSE, 
  boxplots=FALSE, data=UniveralBank)
```

```{r}
scatterplot(PersonalLoan~Income, regLine=FALSE, smooth=FALSE, 
  boxplots=FALSE, data=UniveralBank)
```

```{r}
scatterplot(PersonalLoan~Income, regLine=FALSE, smooth=list(span=0.5, 
  spread=FALSE), boxplots=FALSE, data=UniveralBank)
```

```{r}
GLM.Logit.UniversalBank <- glm(PersonalLoan ~ Income + Age + Family + CCAvg,
   family=binomial(logit), data=UniveralBank)
summary(GLM.Logit.UniversalBank)
exp(coef(GLM.Logit.UniversalBank))  
  # Exponentiated coefficients ("odds ratios")
```

```{r}

